name: zooplugs
favicon: null
layout_spectrum: 0.2868999014608562
typography_spectrum: 0.921565949684009
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.7077473318204284
  lightness: 0.682307897368446
  saturation: 0.005161661189049482
  rhythmicContrast: 0.17691227584145963
purpose: []
